import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the <a href="">Blog!</a>
        </h1>

        <p className={styles.description}>
          <strong>Case Study: </strong> SSR and Web Animations.
          <code className={styles.code}>pages/svganime.tsx</code>
        </p>

        <div className={styles.grid}>
          <Link href="/svganime" passHref>
            <div className={styles.card}>
            <h2>SVG Page Animation &rarr;</h2>
            <p>Explore here.</p>
            </div>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href=""
          target="_blank"
          rel="noopener noreferrer"
        >
          Dhrumil Limbad
        </a>
      </footer>
    </div>
  )
}

export default Home
